apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-observability
  namespace: istio-system
spec:
  metrics:
    overrides:
      - match:
          metric: ALL_METRICS
        enabled: true
  tracing:
    providers:
      - name: jaeger
        zipkin:
          address: "jaeger-collector.observability.svc.cluster.local:9411"
