apiVersion: v1
kind: ConfigMap
metadata:
  name: falcosidekick-config
  namespace: falco
data:
  config.yaml: |-
    slack:
      enabled: true
      webhookurl: "<SLACK_WEBHOOK_URL>"   # Replace with your webhook
      minimumpriority: "warning"
