apiVersion: v1
kind: ConfigMap
metadata:
  name: falcosidekick-config
  namespace: falco
data:
  config.yaml: |-
    loki:
      enabled: true
      hostPort: "http://loki.observability.svc.cluster.local:3100"
      minimumpriority: "warning"
