apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.large", "m5.large"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: my-eks-cluster
    securityGroupSelector:
      karpenter.sh/discovery: my-eks-cluster
  limits:
    resources:
      cpu: 1000
  ttlSecondsAfterEmpty: 60
