apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: zone-a
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: my-eks-cluster
    securityGroupSelector:
      karpenter.sh/discovery: my-eks-cluster
  ttlSecondsAfterEmpty: 60
