adminUser: admin
adminPassword: observability123
persistence:
  enabled: true
  size: 5Gi
sidecar:
  dashboards:
    enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.observability.svc.cluster.local
