server:
  persistentVolume:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
alertmanager:
  enabled: true
rbac:
  create: true
serviceAccounts:
  server:
    create: true
    name: prometheus-server
