apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["m5.large","m5.xlarge"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: demo-eks
  ttlSecondsAfterEmpty: 30
  limits:
    resources:
      cpu: 1000
