apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-controller
  namespace: karpenter
  annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::<Add AWS ACCOUNT_ID>:role/KarpenterControllerRole
